landing_page/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'landing_page'

urlpatterns = [
    path('', views.index, name="home"),
]

tugas6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
]

landing_page/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
    comment = models.CharField(max_length = 255)
    date = models.DateTimeField( auto_now_add = True)

    def __str__(self):
        return "{}".format(self.comment)

landing_page/forms.py
from django import forms

from .models import PostModel

class PostForm(forms.ModelForm):
  class Meta:
    model = PostModel
    fields = [
      'comment',
    ]

    widgets = {
      'namaKegiatan' : forms.TextInput (
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'isi dengan keluh kesah kamu'
                }
            ),      
    }

landing_page/views.py
from django.shortcuts import render,redirect
from .forms import PostForm
from .models import PostModel

# Create your views here.

def index(request):
  post_form = PostForm(request.POST or None)
  post = PostModel.objects.all()

  if request.method == 'POST' :
    if post_form.is_valid():
      post_form.save()
  
  context = {
    'posts' : post,
    'post_form' : post_form,
  }

  return render(request, 'pages/index.html',context)

landing_page/templates/pages/index.html
{% load static %}

<meta http-equiv="pragma" content = "no-cache"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>My Website</title>

</head>
<body data-spy = "scroll" data-target="#navbarResponsive">
  {% include "pages/snipsets/navbar.html" %}
    <!--Start Landing Page-->
    <div class="landing">
      <div class="home-wrap">
        <div class="home-inner">
          </div>
      </div>
    </div>

    <div class="caption text-center">
      <div class = "col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <h1>Halo!</h1>
        <h3>Apa kabar kamu hari ini?</h3>
      </div>
      <div class= "col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <div class = "caption-form">
            <form method = "POST">
                {% csrf_token %}
                <form>
                    <div class="form-group row col-lg-12">
                          <div id="id_comment" class="col-sm-12">
                              {{post_form.comment}}
                          </div>
                    </div>      
                    <div class ="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
                      <button type ="submit" class="tombol" class="btn btn-outline-light" href= "">Submit</button>
                    </div>
                </form>
              </form>
        </div>
      </div>
    </div>
    
    <div class = "comment-container text-center">
      <h1>Your Post</h1>
      {% for post in posts %}
      <div class = "col col-sm-6 col-md-6 col-lg-12">
        <h3>{{post.comment}}</h3>
        <h6>{{post.date}}</h6>
      </div>
      {% endfor%}
    </div>



      <!--End Landing Page-->
</body>
</html>

landing_page/templates/pages/snipsets/javascript.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

landing_page/templates/pages/snipsets/navbar.html
{% load static %}
<link rel="stylesheet" href = "{% static 'landing/css/style.css' %}" >
<link rel="stylesheet" href = "{% static 'landing/css/style/fixed.css' %}">

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <a class="navbar-brand" href="">iKnow</a>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href= "" >Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href= "" >Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href= "" >Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href= "" >Home</a>
        </li>
      </ul>
    </div>
</nav>

{% include "pages/snipsets/javascript.html" %}